import Head from 'next/head'
import TopCards from '@/components/TopCards'
import Transaction from '@/components/Transaction'
import AnalyticsChart from '@/components/charts/AnalyticsChart'
import Layout from '@/layouts/MainLayout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopCards />
        <div className='flex justify-between items-start gap-10 flex-col xl:flex-row'>
          <div className='max-w-[685px] w-full'>
            <Transaction />
          </div>
          <div className='max-w-[665px] w-full'>
            <AnalyticsChart />
          </div>
        </div>
      </Layout>
    </>
  )
}
