import Head from 'next/head'
import TopCards from '@/components/TopCards'
import Transaction from '@/components/Transaction'
import AnalyticsChart from '@/components/charts/AnalyticsChart'
import Layout from '@/layouts/MainLayout'
import TransactionService from '../services/TransactionService'
import { GetServerSideProps } from "next";
import { ITransactionData } from '../types/TransactionType';
import { IError } from '../types/RequestsType';

interface HomeType {
  transactionData: {
    data: ITransactionData[];
    error: IError;
  }
}


export default function Home({ transactionData }: HomeType) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopCards />
        <div className='flex justify-between items-start gap-10 flex-col xl:flex-row'>
          <div className='max-w-[685px] w-full'>
            <Transaction transactionData={transactionData} />
          </div>
          <div className='max-w-[665px] w-full'>
            <AnalyticsChart />
          </div>
        </div>
      </Layout>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {

  const transactionResponse = await TransactionService.GetTransactions();

  return {
    props: {
      transactionData: {
        data: transactionResponse?.data?.transactions ?? null,
        error: transactionResponse?.error ?? null,
      }
    }
  }

}
